import { Patient } from '@/types';

// Imagens de exemplo (placeholders SVG)
const createMockImage = (color: string, label: string) => {
  return `data:image/svg+xml;base64,${btoa(`
    <svg width="400" height="300" xmlns="http://www.w3.org/2000/svg">
      <rect width="400" height="300" fill="${color}"/>
      <circle cx="200" cy="150" r="80" fill="rgba(255,255,255,0.3)"/>
      <circle cx="180" cy="130" r="30" fill="rgba(255,255,255,0.5)"/>
      <circle cx="220" cy="130" r="30" fill="rgba(255,255,255,0.5)"/>
      <text x="50%" y="85%" font-size="16" fill="white" text-anchor="middle" font-family="Arial">${label}</text>
    </svg>
  `)}`;
};

// Pacientes pendentes de laudo (para Fila de Laudos)
export const mockPatients: Patient[] = [
  {
    id: 'mock-patient-1',
    name: 'Maria Silva Santos',
    cpf: '123.456.789-01',
    birthDate: '1978-03-15',
    examDate: '2024-11-15',
    location: 'UPA Central - São Paulo',
    technicianName: 'Carlos Mendes',
    status: 'pending',
    createdAt: '2024-11-15T09:30:00.000Z',
    images: [
      {
        id: 'img-1-1',
        data: createMockImage('#0a5ea7', 'Retinografia OD - Maria Silva'),
        fileName: 'retinografia-od-maria.jpg',
        uploadedAt: '2024-11-15T09:30:00.000Z',
      },
      {
        id: 'img-1-2',
        data: createMockImage('#0284c7', 'Retinografia OE - Maria Silva'),
        fileName: 'retinografia-oe-maria.jpg',
        uploadedAt: '2024-11-15T09:30:00.000Z',
      },
      {
        id: 'img-1-3',
        data: createMockImage('#0369a1', 'Campo Visual - Maria Silva'),
        fileName: 'campo-visual-maria.jpg',
        uploadedAt: '2024-11-15T09:30:00.000Z',
      },
    ],
  },
  {
    id: 'mock-patient-2',
    name: 'João Pedro Oliveira',
    cpf: '987.654.321-02',
    birthDate: '1965-08-22',
    examDate: '2024-11-16',
    location: 'Hospital Santa Casa - Rio de Janeiro',
    technicianName: 'Ana Paula Costa',
    status: 'pending',
    createdAt: '2024-11-16T10:15:00.000Z',
    images: [
      {
        id: 'img-2-1',
        data: createMockImage('#059669', 'Retinografia OD - João Pedro'),
        fileName: 'retinografia-od-joao.jpg',
        uploadedAt: '2024-11-16T10:15:00.000Z',
      },
      {
        id: 'img-2-2',
        data: createMockImage('#10b981', 'Retinografia OE - João Pedro'),
        fileName: 'retinografia-oe-joao.jpg',
        uploadedAt: '2024-11-16T10:15:00.000Z',
      },
      {
        id: 'img-2-3',
        data: createMockImage('#34d399', 'OCT - João Pedro'),
        fileName: 'oct-joao.jpg',
        uploadedAt: '2024-11-16T10:15:00.000Z',
      },
    ],
  },
  {
    id: 'mock-patient-3',
    name: 'Ana Carolina Ferreira',
    cpf: '456.789.123-03',
    birthDate: '1990-12-05',
    examDate: '2024-11-17',
    location: 'Clínica Oftalmológica Visão - Belo Horizonte',
    technicianName: 'Roberto Lima',
    status: 'pending',
    createdAt: '2024-11-17T14:20:00.000Z',
    images: [
      {
        id: 'img-3-1',
        data: createMockImage('#7c3aed', 'Retinografia OD - Ana Carolina'),
        fileName: 'retinografia-od-ana.jpg',
        uploadedAt: '2024-11-17T14:20:00.000Z',
      },
      {
        id: 'img-3-2',
        data: createMockImage('#8b5cf6', 'Retinografia OE - Ana Carolina'),
        fileName: 'retinografia-oe-ana.jpg',
        uploadedAt: '2024-11-17T14:20:00.000Z',
      },
      {
        id: 'img-3-3',
        data: createMockImage('#a78bfa', 'Angiografia - Ana Carolina'),
        fileName: 'angiografia-ana.jpg',
        uploadedAt: '2024-11-17T14:20:00.000Z',
      },
    ],
  },
  {
    id: 'mock-patient-4',
    name: 'Roberto Carlos Almeida',
    cpf: '321.654.987-04',
    birthDate: '1955-06-30',
    examDate: '2024-11-18',
    location: 'UPA Norte - Brasília',
    technicianName: 'Fernanda Souza',
    status: 'pending',
    createdAt: '2024-11-18T08:45:00.000Z',
    images: [
      {
        id: 'img-4-1',
        data: createMockImage('#dc2626', 'Retinografia OD - Roberto Carlos'),
        fileName: 'retinografia-od-roberto.jpg',
        uploadedAt: '2024-11-18T08:45:00.000Z',
      },
      {
        id: 'img-4-2',
        data: createMockImage('#ef4444', 'Retinografia OE - Roberto Carlos'),
        fileName: 'retinografia-oe-roberto.jpg',
        uploadedAt: '2024-11-18T08:45:00.000Z',
      },
      {
        id: 'img-4-3',
        data: createMockImage('#f87171', 'Topografia - Roberto Carlos'),
        fileName: 'topografia-roberto.jpg',
        uploadedAt: '2024-11-18T08:45:00.000Z',
      },
    ],
  },
];

// Pacientes com laudos completos aguardando encaminhamento (para página de Encaminhamentos)
export const mockPatientsForReferrals: Patient[] = [
  {
    id: 'mock-ref-1',
    name: 'Carlos Eduardo Santos',
    cpf: '111.222.333-44',
    birthDate: '1972-05-20',
    examDate: '2024-11-10',
    location: 'UPA Sul - Curitiba',
    technicianName: 'Juliana Martins',
    status: 'completed',
    createdAt: '2024-11-10T10:30:00.000Z',
    images: [
      {
        id: 'img-ref-1-1',
        data: createMockImage('#f59e0b', 'Retinografia OD - Carlos Eduardo'),
        fileName: 'retinografia-od-carlos.jpg',
        uploadedAt: '2024-11-10T10:30:00.000Z',
      },
      {
        id: 'img-ref-1-2',
        data: createMockImage('#f97316', 'Retinografia OE - Carlos Eduardo'),
        fileName: 'retinografia-oe-carlos.jpg',
        uploadedAt: '2024-11-10T10:30:00.000Z',
      },
      {
        id: 'img-ref-1-3',
        data: createMockImage('#fb923c', 'OCT - Carlos Eduardo'),
        fileName: 'oct-carlos.jpg',
        uploadedAt: '2024-11-10T10:30:00.000Z',
      },
    ],
    report: {
      id: 'report-ref-1',
      patientId: 'mock-ref-1',
      doctorName: 'Dra. Patricia Oliveira',
      findings: 'Presença de microaneurismas e exsudatos duros na região macular bilateral. Áreas de isquemia retiniana identificadas.',
      diagnosis: 'Retinopatia diabética não proliferativa moderada bilateral.',
      recommendations: 'Encaminhamento para especialista em retina. Controle rigoroso da glicemia. Retorno em 3 meses para acompanhamento.',
      diagnosticConditions: {
        normal: false,
        drMild: false,
        drModerate: true,
        drSevere: false,
        drProliferative: false,
        glaucomaSuspect: false,
        hrMild: false,
        hrModerate: false,
        hrSevere: false,
        hypertensiveRetinopathy: false,
        tumor: false,
        others: false,
      },
      completedAt: '2024-11-10T14:20:00.000Z',
    },
  },
  {
    id: 'mock-ref-2',
    name: 'Beatriz Rodrigues Lima',
    cpf: '555.666.777-88',
    birthDate: '1985-09-14',
    examDate: '2024-11-12',
    location: 'Hospital Regional - Fortaleza',
    technicianName: 'Marcos Pereira',
    status: 'completed',
    createdAt: '2024-11-12T08:15:00.000Z',
    images: [
      {
        id: 'img-ref-2-1',
        data: createMockImage('#ec4899', 'Retinografia OD - Beatriz'),
        fileName: 'retinografia-od-beatriz.jpg',
        uploadedAt: '2024-11-12T08:15:00.000Z',
      },
      {
        id: 'img-ref-2-2',
        data: createMockImage('#f472b6', 'Retinografia OE - Beatriz'),
        fileName: 'retinografia-oe-beatriz.jpg',
        uploadedAt: '2024-11-12T08:15:00.000Z',
      },
      {
        id: 'img-ref-2-3',
        data: createMockImage('#f9a8d4', 'Campo Visual - Beatriz'),
        fileName: 'campo-visual-beatriz.jpg',
        uploadedAt: '2024-11-12T08:15:00.000Z',
      },
    ],
    report: {
      id: 'report-ref-2',
      patientId: 'mock-ref-2',
      doctorName: 'Dr. Fernando Alves',
      findings: 'Aumento da escavação do disco óptico bilateral (relação E/D: 0.7 OD, 0.8 OE). Adelgaçamento da camada de fibras nervosas.',
      diagnosis: 'Glaucoma primário de ângulo aberto bilateral.',
      recommendations: 'Encaminhamento urgente para especialista em glaucoma. Necessário início de terapia hipotensora ocular. Acompanhamento mensal.',
      diagnosticConditions: {
        normal: false,
        drMild: false,
        drModerate: false,
        drSevere: false,
        drProliferative: false,
        glaucomaSuspect: true,
        hrMild: false,
        hrModerate: false,
        hrSevere: false,
        hypertensiveRetinopathy: false,
        tumor: false,
        others: false,
      },
      completedAt: '2024-11-12T11:45:00.000Z',
    },
  },
  {
    id: 'mock-ref-3',
    name: 'José Antonio Ferreira',
    cpf: '999.888.777-66',
    birthDate: '1948-03-08',
    examDate: '2024-11-14',
    location: 'Clínica Visão Clara - Porto Alegre',
    technicianName: 'Sandra Oliveira',
    status: 'completed',
    createdAt: '2024-11-14T15:20:00.000Z',
    images: [
      {
        id: 'img-ref-3-1',
        data: createMockImage('#14b8a6', 'Retinografia OD - José Antonio'),
        fileName: 'retinografia-od-jose.jpg',
        uploadedAt: '2024-11-14T15:20:00.000Z',
      },
      {
        id: 'img-ref-3-2',
        data: createMockImage('#2dd4bf', 'Retinografia OE - José Antonio'),
        fileName: 'retinografia-oe-jose.jpg',
        uploadedAt: '2024-11-14T15:20:00.000Z',
      },
      {
        id: 'img-ref-3-3',
        data: createMockImage('#5eead4', 'OCT Macular - José Antonio'),
        fileName: 'oct-macular-jose.jpg',
        uploadedAt: '2024-11-14T15:20:00.000Z',
      },
    ],
    report: {
      id: 'report-ref-3',
      patientId: 'mock-ref-3',
      doctorName: 'Dra. Mariana Costa',
      findings: 'Drusas maculares bilaterais. Alterações pigmentares na região macular. Opacificação cristaliniana nuclear bilateral moderada.',
      diagnosis: 'Degeneração macular relacionada à idade (DMRI) seca inicial bilateral. Catarata nuclear bilateral.',
      recommendations: 'Encaminhamento para avaliação de cirurgia de catarata. Suplementação com vitaminas antioxidantes. Acompanhamento semestral da DMRI.',
      diagnosticConditions: {
        normal: false,
        drMild: false,
        drModerate: false,
        drSevere: false,
        drProliferative: false,
        glaucomaSuspect: false,
        hrMild: false,
        hrModerate: false,
        hrSevere: false,
        hypertensiveRetinopathy: false,
        tumor: false,
        others: true,
      },
      completedAt: '2024-11-14T16:30:00.000Z',
    },
  },
];

// Pacientes com laudos E encaminhamentos completos (para página de Resultados)
export const mockPatientsWithReferrals: Patient[] = [
  {
    id: 'mock-result-1',
    name: 'Helena Cristina Souza',
    cpf: '222.333.444-55',
    birthDate: '1968-11-25',
    examDate: '2024-11-05',
    location: 'UPA Central - Salvador',
    technicianName: 'Ricardo Santos',
    status: 'completed',
    createdAt: '2024-11-05T09:00:00.000Z',
    images: [
      {
        id: 'img-result-1-1',
        data: createMockImage('#3b82f6', 'Retinografia OD - Helena'),
        fileName: 'retinografia-od-helena.jpg',
        uploadedAt: '2024-11-05T09:00:00.000Z',
      },
      {
        id: 'img-result-1-2',
        data: createMockImage('#60a5fa', 'Retinografia OE - Helena'),
        fileName: 'retinografia-oe-helena.jpg',
        uploadedAt: '2024-11-05T09:00:00.000Z',
      },
      {
        id: 'img-result-1-3',
        data: createMockImage('#93c5fd', 'Angiografia - Helena'),
        fileName: 'angiografia-helena.jpg',
        uploadedAt: '2024-11-05T09:00:00.000Z',
      },
    ],
    report: {
      id: 'report-result-1',
      patientId: 'mock-result-1',
      doctorName: 'Dr. Eduardo Mendes',
      findings: 'Neovascularização retiniana bilateral. Hemorragias pré-retinianas. Edema macular clinicamente significativo.',
      diagnosis: 'Retinopatia diabética proliferativa bilateral com edema macular diabético.',
      recommendations: 'Encaminhamento emergencial para retina. Necessária fotocoagulação a laser e possível injeção intravítrea de anti-VEGF.',
      diagnosticConditions: {
        normal: false,
        drMild: false,
        drModerate: false,
        drSevere: false,
        drProliferative: true,
        glaucomaSuspect: false,
        hrMild: false,
        hrModerate: false,
        hrSevere: false,
        hypertensiveRetinopathy: false,
        tumor: false,
        others: false,
      },
      completedAt: '2024-11-05T13:15:00.000Z',
    },
    referral: {
      id: 'referral-result-1',
      patientId: 'mock-result-1',
      referredBy: 'Dra. Ana Paula Vieira',
      referralDate: '2024-11-05T14:30:00.000Z',
      specialty: 'Retina',
      urgency: 'emergency',
      notes: 'Paciente com retinopatia proliferativa grave. Necessita tratamento imediato para preservação visual.',
      status: 'scheduled',
    },
  },
  {
    id: 'mock-result-2',
    name: 'Paulo Henrique Costa',
    cpf: '666.777.888-99',
    birthDate: '1960-07-12',
    examDate: '2024-11-08',
    location: 'Hospital Universitário - Recife',
    technicianName: 'Carla Mendes',
    status: 'completed',
    createdAt: '2024-11-08T11:30:00.000Z',
    images: [
      {
        id: 'img-result-2-1',
        data: createMockImage('#8b5cf6', 'Retinografia OD - Paulo'),
        fileName: 'retinografia-od-paulo.jpg',
        uploadedAt: '2024-11-08T11:30:00.000Z',
      },
      {
        id: 'img-result-2-2',
        data: createMockImage('#a78bfa', 'Retinografia OE - Paulo'),
        fileName: 'retinografia-oe-paulo.jpg',
        uploadedAt: '2024-11-08T11:30:00.000Z',
      },
      {
        id: 'img-result-2-3',
        data: createMockImage('#c4b5fd', 'Paquimetria - Paulo'),
        fileName: 'paquimetria-paulo.jpg',
        uploadedAt: '2024-11-08T11:30:00.000Z',
      },
    ],
    report: {
      id: 'report-result-2',
      patientId: 'mock-result-2',
      doctorName: 'Dra. Juliana Rodrigues',
      findings: 'Pressão intraocular elevada (28mmHg OD, 26mmHg OE). Escavação aumentada do disco óptico. Defeitos no campo visual periférico.',
      diagnosis: 'Glaucoma primário de ângulo aberto bilateral avançado.',
      recommendations: 'Encaminhamento urgente para glaucoma. Avaliação para procedimento cirúrgico (trabeculectomia). Iniciar terapia tríplice.',
      diagnosticConditions: {
        normal: false,
        drMild: false,
        drModerate: false,
        drSevere: false,
        drProliferative: false,
        glaucomaSuspect: true,
        hrMild: false,
        hrModerate: false,
        hrSevere: false,
        hypertensiveRetinopathy: false,
        tumor: false,
        others: false,
      },
      completedAt: '2024-11-08T15:00:00.000Z',
    },
    referral: {
      id: 'referral-result-2',
      patientId: 'mock-result-2',
      referredBy: 'Dr. Roberto Silva',
      referralDate: '2024-11-08T16:00:00.000Z',
      specialty: 'Glaucoma',
      urgency: 'urgent',
      notes: 'Glaucoma avançado com risco de perda visual permanente. Necessita avaliação cirúrgica com urgência.',
      status: 'pending',
    },
  },
  {
    id: 'mock-result-3',
    name: 'Margarida Flores Silva',
    cpf: '333.444.555-66',
    birthDate: '1952-02-18',
    examDate: '2024-11-09',
    location: 'Clínica Oftalmológica Premium - Manaus',
    technicianName: 'Felipe Barbosa',
    status: 'completed',
    createdAt: '2024-11-09T10:00:00.000Z',
    images: [
      {
        id: 'img-result-3-1',
        data: createMockImage('#ef4444', 'Retinografia OD - Margarida'),
        fileName: 'retinografia-od-margarida.jpg',
        uploadedAt: '2024-11-09T10:00:00.000Z',
      },
      {
        id: 'img-result-3-2',
        data: createMockImage('#f87171', 'Retinografia OE - Margarida'),
        fileName: 'retinografia-oe-margarida.jpg',
        uploadedAt: '2024-11-09T10:00:00.000Z',
      },
      {
        id: 'img-result-3-3',
        data: createMockImage('#fca5a5', 'Biomicroscopia - Margarida'),
        fileName: 'biomicroscopia-margarida.jpg',
        uploadedAt: '2024-11-09T10:00:00.000Z',
      },
    ],
    report: {
      id: 'report-result-3',
      patientId: 'mock-result-3',
      doctorName: 'Dr. Alexandre Pinto',
      findings: 'Opacificação cristaliniana nuclear e cortical bilateral avançada. Acuidade visual reduzida (20/100 AO). Fundoscopia prejudicada pela opacidade cristaliniana.',
      diagnosis: 'Catarata senil bilateral madura.',
      recommendations: 'Encaminhamento para cirurgia de catarata bilateral. Prioridade para olho direito. Sem contraindicações cirúrgicas identificadas.',
      diagnosticConditions: {
        normal: false,
        drMild: false,
        drModerate: false,
        drSevere: false,
        drProliferative: false,
        glaucomaSuspect: false,
        hrMild: false,
        hrModerate: false,
        hrSevere: false,
        hypertensiveRetinopathy: false,
        tumor: false,
        others: true,
      },
      completedAt: '2024-11-09T12:30:00.000Z',
    },
    referral: {
      id: 'referral-result-3',
      patientId: 'mock-result-3',
      referredBy: 'Téc. Mariana Alves',
      referralDate: '2024-11-09T14:00:00.000Z',
      specialty: 'Catarata',
      urgency: 'routine',
      notes: 'Paciente com catarata bilateral madura. Deseja realizar cirurgia o quanto antes devido à perda visual significativa.',
      status: 'scheduled',
    },
  },
];
