/**
 * fix_cpf_gender.js - Sync CPF and gender from patient_details.json to DB
 *
 * The exam endpoint (/examData/list) does NOT reliably return CPF and gender.
 * The patient endpoint (/patient/list) has the complete data.
 * This script reads patient_details.json (generated by fetch_patient_details.py)
 * and updates the DB.
 *
 * Also normalizes gender values:
 *   EyerCloud API returns: "male", "female", "" (or missing)
 *   DB currently has: "male", "female", null (inconsistent with UI)
 *   UI form uses: "Masculino", "Feminino", "Outro", "Não informado"
 *   UI display (medical) compares: 'Masculino', 'Feminino' (after this fix)
 *
 * This script normalizes all gender values to Portuguese:
 *   "male" -> "Masculino"
 *   "female" -> "Feminino"
 *
 * Usage:
 *   node scripts/fix_cpf_gender.js              # Preview
 *   node scripts/fix_cpf_gender.js --execute    # Apply
 */

const { PrismaClient } = require('@prisma/client');
const fs = require('fs');
const path = require('path');

const prisma = new PrismaClient();
const execute = process.argv.includes('--execute');
console.log(execute ? '=== EXECUTE ===' : '=== PREVIEW ===');

function normalize(name) {
  return name
    .toUpperCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

// Map EyerCloud gender values to app's Portuguese values
function mapGender(eyerCloudGender) {
  if (!eyerCloudGender) return null;
  const g = eyerCloudGender.toLowerCase().trim();
  if (g === 'male' || g === 'm' || g === 'masculino') return 'Masculino';
  if (g === 'female' || g === 'f' || g === 'feminino') return 'Feminino';
  if (g === 'outro' || g === 'other' || g === 'outros') return 'Outro';
  return null; // Unknown value, don't update
}

async function main() {
  // Try to load patient_details.json first, fall back to direct DB gender fix
  const detailsPath = path.join(__dirname, 'eyercloud_downloader', 'patient_details.json');
  let detailsMap = null;

  if (fs.existsSync(detailsPath)) {
    detailsMap = JSON.parse(fs.readFileSync(detailsPath, 'utf8'));
    console.log(`Loaded ${Object.keys(detailsMap).length} patients from patient_details.json\n`);
  } else {
    console.log('patient_details.json not found - will only normalize existing gender values');
    console.log('Run fetch_patient_details.py first to also sync CPF and gender from EyerCloud\n');
  }

  // Build name -> details lookup from patient_details.json
  const nameToDetails = {};
  if (detailsMap) {
    for (const [patId, detail] of Object.entries(detailsMap)) {
      const name = detail.name;
      if (!name) continue;
      const norm = normalize(name);
      // Keep the entry with most data
      const existing = nameToDetails[norm];
      if (!existing) {
        nameToDetails[norm] = { ...detail, eyerCloudId: patId };
      } else {
        const newScore = (detail.cpf ? 1 : 0) + (detail.gender ? 1 : 0) + (detail.birthday ? 1 : 0);
        const oldScore = (existing.cpf ? 1 : 0) + (existing.gender ? 1 : 0) + (existing.birthday ? 1 : 0);
        if (newScore > oldScore) {
          nameToDetails[norm] = { ...detail, eyerCloudId: patId };
        }
      }
    }
  }

  // Get all patients from DB
  const patients = await prisma.patient.findMany({
    select: { id: true, name: true, cpf: true, gender: true, birthDate: true }
  });

  let cpfUpdated = 0;
  let genderUpdated = 0;
  let genderNormalized = 0;
  let unchanged = 0;
  let notFound = 0;

  for (const pat of patients) {
    const norm = normalize(pat.name);
    const cloudData = nameToDetails[norm];
    const updates = {};
    const changes = [];

    // --- CPF ---
    // Update CPF if missing in DB but available from EyerCloud
    if (cloudData && cloudData.cpf) {
      const dbCpf = (pat.cpf || '').trim();
      const cloudCpf = cloudData.cpf.trim();
      if (!dbCpf || dbCpf === 'PENDENTE') {
        updates.cpf = cloudCpf;
        changes.push(`cpf: "${dbCpf || 'null'}" -> "${cloudCpf}"`);
        cpfUpdated++;
      }
    }

    // --- Gender ---
    const dbGender = (pat.gender || '').trim();
    let newGender = null;

    // First try to get gender from EyerCloud patient details
    if (cloudData && cloudData.gender) {
      newGender = mapGender(cloudData.gender);
    }

    // If no cloud data, normalize existing DB value
    if (!newGender && dbGender) {
      newGender = mapGender(dbGender);
    }

    if (newGender && newGender !== dbGender) {
      updates.gender = newGender;
      if (!dbGender || dbGender === 'null') {
        changes.push(`gender: null -> "${newGender}"`);
        genderUpdated++;
      } else {
        changes.push(`gender: "${dbGender}" -> "${newGender}"`);
        genderNormalized++;
      }
    }

    // Apply updates
    if (Object.keys(updates).length > 0) {
      console.log(`  UPDATE: ${pat.name}`);
      for (const change of changes) {
        console.log(`          ${change}`);
      }

      if (execute) {
        await prisma.patient.update({
          where: { id: pat.id },
          data: {
            ...updates,
            updatedAt: new Date()
          }
        });
      }
    } else {
      if (!cloudData && detailsMap) {
        notFound++;
      } else {
        unchanged++;
      }
    }
  }

  console.log(`\n=== SUMMARY ===`);
  console.log(`Total patients in DB: ${patients.length}`);
  console.log(`CPF updated: ${cpfUpdated}`);
  console.log(`Gender set (was null): ${genderUpdated}`);
  console.log(`Gender normalized (male->Masculino etc): ${genderNormalized}`);
  console.log(`Unchanged: ${unchanged}`);
  if (detailsMap) {
    console.log(`Not found in patient_details.json: ${notFound}`);
  }

  if (!execute && (cpfUpdated + genderUpdated + genderNormalized) > 0) {
    console.log(`\nRun with --execute to apply ${cpfUpdated + genderUpdated + genderNormalized} updates`);
  }

  await prisma.$disconnect();
}

main();
